export const MessagingErrorCode = {
  HANDSHAKE_REQUIRED: 'HANDSHAKE_REQUIRED',
  SENDER_ID_MISMATCH: 'SENDER_ID_MISMATCH',
  RECIPIENT_NOT_FOUND: 'RECIPIENT_NOT_FOUND',
  RECIPIENT_PROJECT_MISMATCH: 'RECIPIENT_PROJECT_MISMATCH',
  RECIPIENT_OFFLINE: 'RECIPIENT_OFFLINE',
  PROJECT_MISMATCH: 'PROJECT_MISMATCH',
} as const;

export type MessagingErrorCode = (typeof MessagingErrorCode)[keyof typeof MessagingErrorCode];
