import { HEDERA_TESTNET_CAIP2, HEDERA_TESTNET_USDC, HEDERA_USDC_DECIMALS } from '@x402/hedera';

export const PAYMENT_CONFIG = {
  NETWORK: process.env.HEDERA_NETWORK || HEDERA_TESTNET_CAIP2 || 'hedera:testnet',
  USDC_TOKEN_ID: process.env.HEDERA_USDC_TOKEN_ID || HEDERA_TESTNET_USDC || '0.0.429274',
  USDC_DECIMALS: HEDERA_USDC_DECIMALS || 6,
  RECEIVER_ADDRESS: process.env.HEDERA_PAYMENT_RECEIVER || '0.0.500123',
  DEFAULT_PRICE_USDC: '0.001',
  DEFAULT_ATOMIC_AMOUNT: '1000', // 0.001 USDC * 10^6
  FACILITATOR_URL: process.env.X402_FACILITATOR_URL || 'https://testnet.facilitator.x402.org',
  SCHEME: 'exact',
};
