export const HandshakeErrorCode = {
  HANDSHAKE_REQUIRED: 'HANDSHAKE_REQUIRED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_NOT_OWNED: 'AGENT_NOT_OWNED',
  AGENT_PROJECT_MISMATCH: 'AGENT_PROJECT_MISMATCH',
  PROJECT_ACCESS_DENIED: 'PROJECT_ACCESS_DENIED',
  INVALID_CAPABILITIES: 'INVALID_CAPABILITIES',
  HANDSHAKE_ALREADY_COMPLETED: 'HANDSHAKE_ALREADY_COMPLETED',
  UNSUPPORTED_PROTOCOL_VERSION: 'UNSUPPORTED_PROTOCOL_VERSION',
} as const;

export type HandshakeErrorCode = (typeof HandshakeErrorCode)[keyof typeof HandshakeErrorCode];
